### ISSUE TITLE
BSTabs: missing data attributes in dropdown

### ISSUE THREAD

**Issue by nark** [lekoala/bs-companion#1]
Hey,

I'm trying to use BsTabs in the context of a Ruby on Rails application with Turbo from Hotwire and unfortunately data attributes setup within my tabs links are missing in their dropdown items equivalent. Any idea how to fix that?

Also, I would like to overwrite `BsTabs.handleEvent()` method with my own implementation but I can't find any way of doing that. Is it possible?

Very nice work btw!

**Comment by lekoala** [comment]
@nark hi there,

what do you mean "the data attributes are missing"? you mean they are not copied over from the original tab link ? if so, that's on purpose: these dropdown links are only meant to trigger a click event on the original tabs link. Therefore, they should just work as expected unless you do have some very specific logic.

if you want to overwrite the logic from handleEvent, nothing is preventing you from creating your own subclass with your own logic. if you have some features in your project that could be made globally available at the component level, i'm happy to make the changes if they make sense :-)

**Comment by nark** [comment]
Yes, about data attributes on links, Turbo heavily relies on them in order to setup its configuration. I observed issues when triggering the click event of a link so I assume we can speak of a very specific logic here.

I'll go the subclass way and keep you posted if needed.

Many thanks for your help.

**Comment by lekoala** [comment]
@nark it would be best to try to understand first why turbo is not happy with the event triggered on the original link, because at the moment i don't see why it would behave any differently. it may mean that i do need to do something differently, but maybe the solution is not copying over the data attributes

anyway, hard to tell without seeing the actual issue :-) if you make any findings than can be added to the class let me know

**Comment by lekoala** [comment]
closing this until i have an example to debug
